### ISSUE TITLE
Updated master, getting 500 internal server error

### ISSUE THREAD

**Issue by rainje** [nZEDb/nZEDb#1852]
Hi,

I recently updated my nzedb, I had to change the config file, everything was looking great but when trying to edit releases (in list view, to change categories), I had a php error.

So the first one I found was that there still was a config.php file in the www folder, which made this : 
```
2015/08/28 16:13:29 [error] 2481#0: *1096261 FastCGI sent in stderr: "PHP message: PHP Notice:  Constant DB_SYSTEM already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 6
PHP message: PHP Notice:  Constant DB_HOST already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 7
PHP message: PHP Notice:  Constant DB_PORT already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 8
PHP message: PHP Notice:  Constant DB_SOCKET already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 9
PHP message: PHP Notice:  Constant DB_USER already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 10
PHP message: PHP Notice:  Constant DB_PASSWORD already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 11
PHP message: PHP Notice:  Constant DB_NAME already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 12
PHP message: PHP Notice:  Constant DB_PCONNECT already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 13
PHP message: PHP Notice:  Constant NNTP_USERNAME already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 15
PHP message: PHP Notice:  Constant NNTP_PASSWORD already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 16
PHP message: PHP Notice:  Constant NNTP_SERVER already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 17
PHP message: PHP Notice:  Constant NNTP_PORT already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 18
PHP message: PHP Notice:  Constant NNTP_SSLENABLED already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 20
PHP message: PHP Notice:  Constant NNTP_SOCKET_TIMEOUT already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 22
PHP message: PHP Notice:  Constant NNTP_USERNAME_A already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 24
PHP message: PHP Notice:  Constant NNTP_PASSWORD_A already defined in /var/www/vhosts/LOL/nZEDb/www/config.php on line 25
```

So I removed that old config file and then I had this : 
```
2015/08/28 16:33:50 [error] 2478#0: *1102837 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(./config.php): failed to open stream: No such file or directory in /var/www/vhosts/LOL/nZEDb/www/pages/AdminPage.php on line 3
PHP message: PHP Fatal error:  require_once(): Failed opening required './config.php' (include_path='/var/www/vhosts/LOL/nZEDb/www/:.:/usr/share/php:/usr/share/pear') in /var/www/vhosts/LOL/nZEDb/www/pages/AdminPage.php on line 3" while reading response header from upstream, client: XXX, server: LOL, request: "GET /ajax_release-admin?action=edit&id[]=7670dcdf1b5309d92afd0ebee45d84642ed87d78&from=http%3A%2F%2FLOL%2Fbrowse%3Ft%3D6050 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "LOL", referrer: "http://LOL/browse?t=6050"

```
So I commented the require_once in the AdminPage.php (it seems to be corrected in dev branch) file and now I can edit categories and delete files, but i'm still getting a non blocking error 500 : 

```
2015/08/28 16:49:41 [error] 2479#0: *1107008 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: rageid in /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php on line 22
PHP message: PHP Notice:  Undefined index: imdbid in /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php on line 22
PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error' in /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php:681
#0 /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php(681): PDOStatement->fetchAll()
#1 /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php(658): nzedb\db\DB->queryArray('UPDATE releases...')
#2 /var/www/vhosts/LOL/nZEDb/nzedb/Releases.php(848): nzedb\db\DB->query('UPDATE releases...')
#3 /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php(22): nzedb\Releases->updatemulti(Array, '6070', '', NULL, '', NULL)
#4 /var/www/vhosts/LOL/nZEDb/www/index.php(73): include('/var/www/vhosts...')
  thrown in /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php on line 681" while reading response header from upstream, client: XXX, server: LOL, request: "POST /ajax_release-admin/?action=doedit&id%5B%5D=0d6daf3acd979df889f2fcf4dc196723fb4abadf&from=http%3A%2F%2FLOL%2Fbrowse%3Ft%3D6050&category=6070&grabs=&rageID=&anidbID=&season=&episode=&imdbID= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "LOL", referrer: "http://LOL/browse?t=6050"
```

Not sure what this mysql req is supposed to do (i'm deleting releases in list view) but it's not doing it.

**Comment by ruhllatio** [comment]
I think I see the issue.  Your submission is sending NULL values but we only check for != ''.  I doubt NULL qualifies.  It would be better if I saw the whole query in the failure.

**Comment by rainje** [comment]
How can I give you this? That's all there's in my error.log.

**Comment by ruhllatio** [comment]
If you edit your config.php you can turn on nZEDb_DEBUG and turn on nZEDb_LOG_QUERIES.  Set them to TRUE and it should error the second you try to submit.

**Comment by rainje** [comment]
I had no settings.php so I did cp the example, change both DEBUG & LOG_QUERIES to true and here's the result in my nginx error log:

```
2015/08/28 18:19:15 [error] 2478#0: *1128069 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: release in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 88
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 88
PHP message: PHP Notice:  Undefined index: release in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 95
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 95
PHP message: PHP Notice:  Undefined index: release in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 102
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 102
PHP message: PHP Notice:  Undefined index: release in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 109
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 109
PHP message: PHP Notice:  Undefined index: release in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.tpl.php on line 116
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/LOL/nZEDb/libs/smarty/templates_c/399d50d6763913ce80de3c3d43171eb3ad4bb705_0.file.ajax_release-edit.t
2015/08/28 18:19:22 [error] 2478#0: *1128069 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: rageid in /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php on line 22
PHP message: PHP Notice:  Undefined index: imdbid in /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php on line 22
PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error' in /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php:681
#0 /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php(681): PDOStatement->fetchAll()
#1 /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php(658): nzedb\db\DB->queryArray('UPDATE releases...')
#2 /var/www/vhosts/LOL/nZEDb/nzedb/Releases.php(848): nzedb\db\DB->query('UPDATE releases...')
#3 /var/www/vhosts/LOL/nZEDb/www/pages/ajax_release-admin.php(22): nzedb\Releases->updatemulti(Array, '6050', '', NULL, '', NULL)
#4 /var/www/vhosts/LOL/nZEDb/www/index.php(73): include('/var/www/vhosts...')
  thrown in /var/www/vhosts/LOL/nZEDb/nzedb/db/DB.php on line 681" while reading response header from upstream, client: XXX, server: LOL, request: "POST /ajax_release-admin/?action=doedit&id%5B%5D=b33d40d2e6079187f9c75e79af4da74f5ca7c91a&from=http%3A%2F%2FLOL%2Fbrowse%3Ft%3D6050%26g%3D%26ob%3D%26offset%3D0&category=6050&grabs=&rageID=&anidbID=&season=&episode=&imdbID= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "LOL", referrer: "http://LOL/browse?t=6050&g=&ob=&offset=0"
```

It seems I can't get the full query. Trying looking in resources/logs but it's empty.

So this actually happens when i'm trying to change a release category. I can see the error 500 in the chrome console.

**Comment by ruhllatio** [comment]
resources/logs doesn't populate unless you enable it.  It's the setting in settings.php right below DEBUG.

**Comment by ruhllatio** [comment]
The problem is definitely the preceding lines before the query.  The release information isn't being passed to the admin page, so it is dumping NULL values into the query.

**Comment by rainje** [comment]
Meh.

Now the nzedb.log file is here but only shows:
```
[28/Aug/2015 18:27] [INIT]   [Initiating new log file.]
```

**Comment by ruhllatio** [comment]
Not sure if I fixed this, but this is confirmed working in dev-tv branch.

**Comment by rainje** [comment]
Yes it is.
