### ISSUE TITLE
PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException'

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2374]
[30-Jan-2017 18:09:19 Europe/Amsterdam] PHP Warning:  Error while sending QUERY packet. PID=47720 in /home/public_html/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php on line 403
[30-Jan-2017 18:09:20 Europe/Amsterdam] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'SELECT `Settings`.`value`, `Settings`.`hint` FROM `settings` AS `Settings` WHERE `Settings`.`name` = 'categorizeforeign' AND `Settings`.`subsection` = 'categorise' AND `Settings`.`section` = 'indexer';: MySQL server has gone away' in /home/public_html/nZEDb/libraries/lithium/data/source/Database.php:1591
Stack trace:
#0 /home/public_html/nZEDb/libraries/lithium/aop/Filters.php(229): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /home/public_html/nZEDb/libraries/lithium/data/source/Database.php(1592): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /home/public_html/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(405): lithium\data\source\Database->_error('SELECT `Setting...')
#3 /home/public_html/nZEDb/libraries/lithium/aop/Filters.php(229): lithium\data\source\database\adapter\MySql->lithium\d in /home/public_html/nZEDb/libraries/lithium/data/source/Database.php on line 1591

Anyone seen this before or know what the problem is?

**Comment by niel** [comment]
What branch?
Looks like a MySQL problem. No idea how I can help.

**Comment by Sweepr** [comment]
An older Dev branch, strange thing is that it has been running fine for a half year untill recently i noticed releases stop being created, so after checking the error log's i found that.. probably related.

**Comment by Sweepr** [comment]
Cleared out the Parts_40, Binaries_40 and Collections_40 table's , restarted Tmux and releases started being created again, aswell as NZB's... weird.

**Comment by Sweepr** [comment]
MySQL server has gone away <- Is Key... I recalled i messed around with timeout's in the config.. so increasing timeout's solved it.
