### ISSUE TITLE
More lithium errors after update this morning...

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2420]
Did an upgrade about 20 minutes ago and now I'm stuck with more lithium errors:

```
Fatal error: Uncaught exception 'lithium\core\ConfigException' with message 'The data connection `default` is not configured for model `app\models\Settings`.' in
/var/www/nZEDb/libraries/lithium/data/Model.php:1470 Stack trace:
#0
/var/www/nZEDb/libraries/lithium/data/Model.php(659): lithium\data\Model::connection()
#1 /var/www/nZEDb/app/models/Settings.php(176): app\models\Settings::lithium\data\{closure}(Array)
#2 /var/www/nZEDb/libraries/lithium/data/Model.php(679): app\models\Settings::app\models\{closure}(Array, Object(Closure))
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): app\models\Settings::lithium\data\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/Model.php(682): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure)) #5 /var/www/nZEDb/app/models/Settings.php(251): lithium\data\Model::find('setting', Array) #6 /var/www/nZEDb/app/config/bootstrap/yenc.php(44): app\models\Settings::value('apps..yydecoder...', true) #7 /var/www/nZEDb/app/config/bootstrap.php(90): req in /var/www/nZEDb/libraries/lithium/data/Model.php on line 1470
```

I can't seem to get around it... any tips?

**Comment by stevenmcastano** [comment]
This can be closed. My mistake, I missed the line in the update guide about moving the `install.lock` file.
