### ISSUE TITLE
Settings: APIs.steam_apps.last_update missing AFTER nzedb upgrade

### ISSUE THREAD

**Issue by sspilleman** [nZEDb/nZEDb#2473]
###Expected behaviour
Update works after I upgraded nzedb

###Actual behaviour
Script crashes with:
```
#0 /media/fast/nzedb/nzedb/Steam.php(149): app\models\Settings::value('APIs.steam_apps...')
#1 /media/fast/nzedb/nzedb/Steam.php(106): nzedb\Steam->populateSteamAppsTable()
#2 /media/fast/nzedb/nzedb/Games.php(503): nzedb\Steam->search('DEAD OR ALIVE 5...')
#3 /media/fast/nzedb/nzedb/Games.php(803): nzedb\Games->updateGamesInfo(Array)
#4 /media/fast/nzedb/nzedb/processing/PostProcess.php(186): nzedb\Games->processGamesReleases()
#5 /media/fast/nzedb/nzedb/libraries/Forking.php(882): nzedb\processing\PostProcess->processGames()
#6 /media/fast/nzedb/nzedb/libraries/Forking.php(162): nzedb\libraries\Forking->processSingle()
#7 /media/fast/nzedb/nzedb/libraries/Forking.php(107): nzedb\libraries\Forking->getWork()
#8 /media/fast/nzedb/misc/update/nix/multiprocessing/postprocess.php(22): nzedb\libraries\Forking->processWorkType('postProcess_ama', Array)
```

###Steps to reproduce the behaviour
Update to latest and running: php ./misc/update/nix/multiprocessing/binaries.php 5000000

**Comment by sspilleman** [comment]
In order to get past this, I had to run the following SQL:
```sql
INSERT INTO `settings` (`section`, `subsection`, `name`, `value`, `hint`, `setting`)
VALUES
	('APIs', 'steam_apps', 'last_update', '0', 'The last time a Steam update occurred in unixtime.', 'steamappslastupdate');
```

**Comment by DariusIII** [comment]
What is your nzedb version? 
https://github.com/nZEDb/nZEDb/releases/tag/v0.7.3.1 should have the fix in it.

**Comment by sspilleman** [comment]
I upgraded from v0.7.3.0 to v0.7.3.1

**Comment by sspilleman** [comment]
./zed version all
```
Looking up Git tag version(s)
Hash: 84a81108a9112f0b018215e6696f02bf88f09e3c
XML version: 0.7.3.1
Git version: 0.7.3.1
Looking up SQL patch version(s)
XML version: 482
 DB version: 474
```

**Comment by DariusIII** [comment]
You did not apply all the latest patches, which makes me think you did not do the timezone stuff from releasenotes.

**Comment by sspilleman** [comment]
I did the timezone stuff.... 
```
sudo ./zed update nzedb
Already up-to-date.
Checking database version...
Db: 474,	File: 482
Looking for unprocessed patches...
Processing patch file: /media/fast/nzedb/resources/db/patches/mysql/0475~steam_apps.sql
Info: COMMENT: Create the new steam_apps table
SUCCESS: DROP TABLE IF EXISTS steam_apps;
Error: CREATE TABLE steam_apps (
  name         VARCHAR(255)        NOT NULL DEFAULT '' COMMENT 'Steam application name',
  appid        INT(11) UNSIGNED    NULL COMMENT 'Steam application id',
  PRIMARY KEY (appid, name),
  FULLTEXT INDEX ix_name_ft (name)
)
  ENGINE          = MYISAM
  DEFAULT CHARSET = utf8
  COLLATE = utf8_unicode_ci; Failed \{1171}
	All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```

**Comment by sspilleman** [comment]
I then created the table manually. Looks like the SQL is wrong: 

appid        INT(11) UNSIGNED    NULL COMMENT 'Steam application id'
should be
appid        INT(11) UNSIGNED  **NOT**  NULL COMMENT 'Steam application id'

**Comment by DariusIII** [comment]
Do you use mysql 5.7 maybe?

**Comment by sspilleman** [comment]
Yes!

**Comment by DariusIII** [comment]
Switch to mariadb, as we only support mariadb.

**Comment by niel** [comment]
The SQL is correct. This is caused by a Breaking Change in MySQL 5.7. 
This and other such changes are why we no longer support vanilla MySQL.
