### ISSUE TITLE
Empty NZB's since upgrade

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2479]
###Expected behaviour
None empty NZB's

###Actual behaviour
Same as "Empty NZB when grabbing #2387", but this was closed.
NZB is potentially broken for GUID: message appearing in post process.

###Steps to reproduce the behaviour
Upgrade and message appears.

This exception appears.
PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'DESCRIBE `models`: Table 'nzedb.models' doesn't exist' in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1601
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1602): lithium\aop\Filters::run(Object(app\extensions\adapter\data\source\database\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('DESCRIBE `model...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(409): lithium\aop\Filters::run(Object(app\extensions\adapter\data\source\database\MySql), '_execute', Array, Object(Closure))
#5 /var/www/n in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1601

Few notes.

This is not a code issue but a config/data issue or 3rd party application issue - completely new code checked out and config copied over.  Only started occurring since upgrade from 0.6.8.0 to 0.7.3.1.

Few people have had this issue from previous issues / forum posts, no resolution ever determined from what I can see.

**Comment by EDChurly** [comment]
This one can close.  Cleaning up the various versions of php sorted it.

So for future reference, this is probably a PHP versioning issue. ie. php5 vs php5.6 vs php7.
