### ISSUE TITLE
Movie.php Tmdb ApiToken

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2501]
Updated Dev.  Movies.php won't load.  Receive following error.  Tested and validated by Tmdb key as working and active.

[05-Aug-2017 21:57:35 US/Central] PHP Fatal error:  Uncaught Error: Class 'Tmdb\ApiToken' not found in /var/www/nZEDb/nzedb/Movie.php:170
Stack trace:
#0 /var/www/nZEDb/www/pages/movies.php(11): nzedb\Movie->__construct(Array)
#1 /var/www/nZEDb/www/index.php(87): require_once('/var/www/nZEDb/...')
#2 {main}
  thrown in /var/www/nZEDb/nzedb/Movie.php on line 170

**Comment by scottia** [comment]
Never mind.  Resolved.  Composer libraries were out of date for some reason.
