### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getMilliseconds() on null

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2625]
Running Ubuntu 18.04.  Completely started over fresh.  Only issue I have is as follows.  Appearsto be a valid error, not sure.

[27-Feb-2019 14:29:53 America/Chicago] PHP Fatal error:  Uncaught Error: Call to a member function getMilliseconds() on null in /var/www/nZEDb/nzedb/ReleaseExtra.php:67
Stack trace:
#0 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(2239): nzedb\ReleaseExtra->addFromMediaInfoContainer('63214', Object(Mhor\MediaInfo\Container\MediaInfoContainer))
#1 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(1534): nzedb\processing\post\ProcessAdditional->getMediaInfo('/var/www/nZEDb/...')
#2 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(1436): nzedb\processing\post\ProcessAdditional->_processMediaInfoMessageIDs()
#3 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(746): nzedb\processing\post\ProcessAdditional->_processMessageIDDownloads()
#4 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(566): nzedb\processing\post\ProcessAdditional->_processReleases()
#5 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php(248): nzedb\processing\post\ProcessAdditional->start('', '6')
#6 {main}
  thrown in /var/www/nZEDb/nzedb/ReleaseExtra.php on line 67

**Comment by scottia** [comment]
Thank you !  Closed.
