### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2626]
Branch Dev 

[14-Mar-2019 10:57:14 America/Chicago] PHP Fatal error:  Uncaught RuntimeException in /var/www/nZEDb/libraries/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php:98
Stack trace:
#0 /var/www/nZEDb/libraries/mhor/php-mediainfo/src/MediaInfo.php(37): Mhor\MediaInfo\Runner\MediaInfoCommandRunner->run()
#1 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(2228): Mhor\MediaInfo\MediaInfo->getInfo('/var/www/nZEDb/...', false)
#2 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(2395): nzedb\processing\post\ProcessAdditional->getMediaInfo('/var/www/nZEDb/...')
#3 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(1369): nzedb\processing\post\ProcessAdditional->_processVideoFile('/var/www/nZEDb/...')
#4 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(760): nzedb\processing\post\ProcessAdditional->_processExtractedFiles()
#5 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(566): nzedb\processing\post\ProcessAdditional->_processReleases()
#6 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php(248): nzedb\p in /var/www/nZEDb/libraries/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php on line 98

**Comment by niel** [comment]
Is this frequent, or more of a one off?
I'll take a look, but there's not much I can do with that info except look for any obvious mistakes like typoes.

**Comment by scottia** [comment]
Yes, very frequent.  Happens alot and fill up the logs many times a day.  Over 2 or 3 days have a very large log file to delete.

**Comment by niel** [comment]
OK, it should be a lot easier to get more info then. In particular the expanded version of the stack trace (the part hidden with ellipses above).

**Comment by scottia** [comment]
I don't think I can pull the expanded log, can I?  If so, will do.

**Comment by niel** [comment]
You might have to install x-debug and mess with its settings

**Comment by scottia** [comment]
Well I tried setting up x-debug and phpstorm but I can't figure out.  That error will not go away and ends up freezing up zed.

**Comment by niel** [comment]
You should only need X-Debug, and configure it so it gives expanded details. That will affect the logs too.

**Comment by scottia** [comment]
you have a simple way to run X-Debug for what you need.  I've never used a debugger.  X-Debug extension is installed and configured.  I verified it but am not sure how to activate it or pull a log.  That's why I was using phpstorm.

**Comment by niel** [comment]
It's no different to what you were doing before. i.e. pasting that error log at the top of the post. Just now it should have more info in it if X-Debug is configured correctly ;-)
You'll probably have to read which options to add to x-debug's configuration though, I don't remember which ones off the top of my head.

**Comment by scottia** [comment]
I realized x-debug settings needed to be activated in ZED to run :)

It's running (and freezes) but not providing anymore info in PHP log that before.  Will see what I have once it runs for awhile.  Error is still occurring.

**Comment by scottia** [comment]
Same error.  No extra X-Debug information. 

[28-Mar-2019 09:01:58 America/Chicago] PHP Fatal error:  Uncaught RuntimeException in /var/www/nZEDb/libraries/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php:98
Stack trace:
#0 /var/www/nZEDb/libraries/mhor/php-mediainfo/src/MediaInfo.php(37): Mhor\MediaInfo\Runner\MediaInfoCommandRunner->run()
#1 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(2228): Mhor\MediaInfo\MediaInfo->getInfo('/var/www/nZEDb/...', false)
#2 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(2395): nzedb\processing\post\ProcessAdditional->getMediaInfo('/var/www/nZEDb/...')
#3 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(1369): nzedb\processing\post\ProcessAdditional->_processVideoFile('/var/www/nZEDb/...')
#4 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(760): nzedb\processing\post\ProcessAdditional->_processExtractedFiles()
#5 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php(566): nzedb\processing\post\ProcessAdditional->_processReleases()
#6 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php(248): nzedb\p in /var/www/nZEDb/libraries/mhor/php-mediainfo/src/Runner/MediaInfoCommandRunner.php on line 98

**Comment by Bart39** [comment]
https://github.com/mhor/php-mediainfo/pull/83/files/462d8e9c630289ff4219285f10f7b3edac0026d1

Might be related - is one of the lines mentioned in your error

**Comment by niel** [comment]
@scottia Makes sure that XDebug is actually being loaded. For CLI do: 
`php -m`
to list modules. 
For web create a file called test.php in the .../www directory containing only:
`<?php phpinfo(); ?>`
and got to localhost://test.php page.
