### ISSUE TITLE
Latest Version - Fresh Install No Post Processing

### ISSUE THREAD

**Issue by JReming85** [nZEDb/nZEDb#2634]
###Expected behaviour
Post Processing, Listing viewable on website

###Actual behaviour
No post processing, nothing visible on website

###Steps to reproduce the behaviour
Fresh install, enable all pp stepsand run it.

It will download, add, rename but nothing will show in Releases, or be visible on website, also 0 errors.

**Comment by JReming85** [comment]
finally got some logs after another reinstall

got lots of these
```
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/nzedb/libraries/Forking.php(101): nzedb\db\DB->__construct()
#1 /var/www/nZEDb/misc/update/nix/multiprocessing/binaries.php(12): nzedb\libraries\Forking->processWorkType('binaries', Array)
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/nzedb/PreDb.php(50): nzedb\db\DB->__construct()
#1 /var/www/nZEDb/misc/update/nix/tmux/bin/postprocess_pre.php(6): nzedb\PreDb->__construct(Array)
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/nzedb/ReleaseRemover.php(128): nzedb\db\DB->__construct()
#1 /var/www/nZEDb/misc/testing/Release/removeCrapReleases.php(66): nzedb\ReleaseRemover->__construct()
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/nzedb/libraries/Forking.php(101): nzedb\db\DB->__construct()
#1 /var/www/nZEDb/misc/update/nix/multiprocessing/backfill.php(11): nzedb\libraries\Forking->processWorkType('backfill', Array)
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/misc/update/decrypt_hashes.php(9): nzedb\db\DB->__construct()
#1 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
[25-Jul-2019 10:57:59 America/New_York] PHP Fatal error:  Uncaught RuntimeException: No Database system supplied. Currently this must be one of: mysql,sphinx in /var/www/nZEDb/nzedb/db/DB.php:209
Stack trace:
#0 /var/www/nZEDb/nzedb/libraries/Forking.php(101): nzedb\db\DB->__construct()
#1 /var/www/nZEDb/misc/update/nix/multiprocessing/releases.php(9): nzedb\libraries\Forking->processWorkType('releases')
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 209
```

followed by some of these

```
[25-Jul-2019 11:00:54 America/New_York] PHP Warning:  filesize(): stat failed for /var/www/nZEDb/resources/logs/nzedb.log in /var/www/nZEDb/nzedb/Logger.php on line 540
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\db\DB->queryOneRow() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:83
[25-Jul-2019 11:00:54 America/New_York] PHP   3. nzedb\db\DB->query() /var/www/nZEDb/nzedb/db/DB.php:1128
[25-Jul-2019 11:00:54 America/New_York] PHP   4. nzedb\db\DB->queryArray() /var/www/nZEDb/nzedb/db/DB.php:835
[25-Jul-2019 11:00:54 America/New_York] PHP   5. nzedb\db\DB->queryDirect() /var/www/nZEDb/nzedb/db/DB.php:855
[25-Jul-2019 11:00:54 America/New_York] PHP   6. nzedb\db\DB->echoError() /var/www/nZEDb/nzedb/db/DB.php:999
[25-Jul-2019 11:00:54 America/New_York] PHP   7. nzedb\Logger->log() /var/www/nZEDb/nzedb/db/DB.php:1414
[25-Jul-2019 11:00:54 America/New_York] PHP   8. nzedb\Logger->logMessage() /var/www/nZEDb/nzedb/Logger.php:256
[25-Jul-2019 11:00:54 America/New_York] PHP   9. nzedb\Logger->rotateLog() /var/www/nZEDb/nzedb/Logger.php:465
[25-Jul-2019 11:00:54 America/New_York] PHP  10. filesize() /var/www/nZEDb/nzedb/Logger.php:540
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: binaries_run in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 97
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: backfill in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 108
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: monitor in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 125
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: is_running in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 125
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: postprocess_kill in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 313
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: collections_kill in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 317
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: compressed in /var/www/nZEDb/nzedb/TmuxOutput.php on line 49
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: is_running in /var/www/nZEDb/nzedb/TmuxOutput.php on line 119
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP   3. nzedb\TmuxOutput->_getHeader() /var/www/nZEDb/nzedb/TmuxOutput.php:51
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: post in /var/www/nZEDb/nzedb/TmuxOutput.php on line 190
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP   3. nzedb\TmuxOutput->_getHeader() /var/www/nZEDb/nzedb/TmuxOutput.php:51
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: post in /var/www/nZEDb/nzedb/TmuxOutput.php on line 190
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP   3. nzedb\TmuxOutput->_getHeader() /var/www/nZEDb/nzedb/TmuxOutput.php:51
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: monitor in /var/www/nZEDb/nzedb/TmuxOutput.php on line 53
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: show_query in /var/www/nZEDb/nzedb/TmuxOutput.php on line 57
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP   2. nzedb\TmuxOutput->updateMonitorPane() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:322
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: is_running in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 325
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Notice:  Undefined index: is_running in /var/www/nZEDb/misc/update/nix/tmux/monitor.php on line 364
[25-Jul-2019 11:00:54 America/New_York] PHP Stack trace:
[25-Jul-2019 11:00:54 America/New_York] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/tmux/monitor.php:0
[25-Jul-2019 11:00:54 America/New_York] PHP Fatal error:  Uncaught lithium\data\model\QueryException: SELECT `Settings`.`value`, `Settings`.`hint` FROM `settings` AS `Settings` WHERE `Settings`.`section` = 'tmux' AND `Settings`.`subsection` = 'running' AND `Settings`.`name` = 'exit';: Table 'nzedb.settings' doesn't exist in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1607
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1608): lithium\aop\Filters::run(Object(app\extensions\adapter\data\source\database\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(407): lithium\data\source\Database->_error('SELECT `Setting...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.ph in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1607
[25-Jul-2019 11:02:27 America/New_York] PHP Fatal error:  Uncaught lithium\data\model\QueryException: SELECT * FROM `predb` AS `Predb` WHERE `Predb`.`title` = 'PILI.Fantasy.War.of.Dragons.S01E14.WEB.x264-WEBTUBE' LIMIT 1;: Table 'nzedb.predb' doesn't exist in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1607
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1608): lithium\aop\Filters::run(Object(app\extensions\adapter\data\source\database\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(407): lithium\data\source\Database->_error('SELECT * FROM `...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(410): lithium\aop\Filters::run(Object(app\extensions\adapter\dat in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1607
```

Any thoughts?

**Comment by niel** [comment]
The first error tells you the problem.
 "No Database system supplied. Currently this must be one of: mysql, sphinx"
Check your .../configuration/ directory and ensure config.php/install.lock files exists.
If they do, check that config.php has a valid entry (it should be 'mysql' and match case) for the DB_SYSTEM constant definition.

**Comment by JReming85** [comment]
I have done this several times… the DB is there (mysql), and all tables are correct.  If you want access to look at it I am more then willing to provide it if needed.

 

But I am thinking about wiping the whole system and trying to reinstall it.

**Comment by Bart39** [comment]
As requested post the contents of your configuration/config.php ....might have to obfuscate/remove your password first though

**Comment by JReming85** [comment]
@Bart39 There never was a request to post the config, just confirm its correct but if you would like to see it here it is:

```
<?php

//=========================
// Config you must change - updated by installer.
//=========================
define('DB_SYSTEM', 'mysql');
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '3306');
define('DB_SOCKET', '/var/run/mysqld/mysqld.sock');
define('DB_USER', '***');
define('DB_PASSWORD', '***');
define('DB_NAME', 'nzedb');
define('DB_PCONNECT', false);

define('NNTP_USERNAME', '***');
define('NNTP_PASSWORD', '***');
define('NNTP_SERVER', 'us.newsgroupdirect.com');
define('NNTP_PORT', '563');
// If you want to use TLS or SSL on the NNTP connection (the NNTP_PORT must be able to support encryption).
define('NNTP_SSLENABLED', true);
// If we lose connection to the NNTP server, this is the time in seconds to wait before giving up.
define('NNTP_SOCKET_TIMEOUT', '120');

define('NNTP_USERNAME_A', '***');
define('NNTP_PASSWORD_A', '***');
define('NNTP_SERVER_A', 'news.usenet.farm');
define('NNTP_PORT_A', '563');
define('NNTP_SSLENABLED_A', true);
define('NNTP_SOCKET_TIMEOUT_A', '120');

// Location to CA bundle file on your system. You can download one here: http://curl.haxx.se/docs/caextract.html
define('nZEDb_SSL_CAFILE', '');
// Path where openssl cert files are stored on your system, this is a fall back if the CAFILE is not found.
define('nZEDb_SSL_CAPATH', '');
// Use the aforementioned CA bundle file to verify remote SSL certificates when connecting to a server using TLS/SSL.
define('nZEDb_SSL_VERIFY_PEER', '');
// Verify the host is who they say they are.
define('nZEDb_SSL_VERIFY_HOST', '');
// Allow self signed certificates. Note this does not work on CURL as CURL does not have this option.
define('nZEDb_SSL_ALLOW_SELF_SIGNED', '1');
```

It works fine in posting the headers to the DB, it just does nothing with them.. I see it renamed a few but nothing is visible on the website in any category
![image](https://user-images.githubusercontent.com/21246660/62014326-899f9780-b16d-11e9-97a9-e0ee67342402.png)

**Comment by Bart39** [comment]
> The first error tells you the problem.
"No Database system supplied. Currently this must be one of: mysql, sphinx"
Check your .../configuration/ directory and ensure config.php, and install.lock files exists.
If they do check that config.php has a valid entry for the DB_SYSTEM constant definition.
**If it does post it here**.

your config looks fine though

**Comment by niel** [comment]
> > The first error tells you the problem.
> > "No Database system supplied. Currently this must be one of: mysql, sphinx"
> > Check your .../configuration/ directory and ensure config.php, and install.lock files exists.
> > If they do check that config.php has a valid entry for the DB_SYSTEM constant definition.
> > **If it does post it here**.
> 
> your config looks fine though

I just looked again myself, and the  **If it does post it here** is missing from my post, WTF. I have no idea how, as I didn't remove it :-(
